
logging:
  file:
    name: C:/elk/spring-boot-elk.log

server:
  port: 9091

spring:
  application:
    name: ServiceTwo
  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)